## Numpy Math Operations

In [1]:
a = [1,2,3]
b = [4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [60]:
import numpy as np


In [61]:
a = np.array([1,2,3])
b = np.array([4,5,6])


In [63]:
print(type(a+b))

<class 'numpy.ndarray'>


In [64]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [65]:
#comparison
print(a>b)
print(a<b)
print(a==b)

[False False False]
[ True  True  True]
[False False False]


In [66]:
ans = a>b
print(ans)
print(type(ans[0]))

[False False False]
<class 'numpy.bool'>


In [67]:
# logical operator
# and, or, not

x = np.array([True, False, True])
y = np.array([False, False, True])

print(np.logical_and(x,y))
print(np.logical_or(x,y))
print(np.logical_not(x))
print(np.logical_xor(x,y))

[False False  True]
[ True False  True]
[False  True False]
[ True False False]


In [69]:
# bitwise opetators
a = np.array([1,2,3])
b = np.array([0,1,1])

print(np.bitwise_and(a,b))
print(np.bitwise_or(a,b))

[0 0 1]
[1 3 3]


In [70]:
# modulus and power

a = np.array([10,20,30])
b = np.array([3,7,4])

print(np.mod(a,b))
print(np.pow(a,b))

[1 6 2]
[      1000 1280000000     810000]


## Scalar operations

In [71]:
celcius = np.array([0, 10, 20, 30])
# to_farenheit = np.array([33.8, 33.8, 33.8, 33.8]) # broadcasting
print(celcius* 9/5 +32)

[32. 50. 68. 86.]


In [72]:
# In python
celcius = [0, 10, 20, 30]
fehrenheit = celcius * 9/5 + 32
print(fehrenheit)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

## Common Math Functions

In [73]:
a = np.array([1,2,3,4])
print(np.sqrt(a))
print(np.exp(a)) # e^1, e^2, e^3 ...
print(np.log(a))
print(np.sin(a))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [74]:
# machine learning
# activation function
# sigmoid


x = np.array([-1, 0, 1])
sigmoid = 1 / (1 + np.exp(-x))
print(sigmoid)

[0.26894142 0.5        0.73105858]


In [75]:
# Aggregation functions
a = np.array([[1,2,3],
             [4,5,6]
             ])

In [76]:
print(np.sum(a))

21


In [77]:
print(np.sum(a, axis=0)) # across all rows, fix the column

[5 7 9]


In [78]:
print(np.sum(a, axis=1)) # across all col, fix the row

[ 6 15]


In [79]:
print(np.sum(a))
print(np.mean(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

21
3.5
1.707825127659933
1
6


## Matrix Operations

In [80]:
# element-wise multiplication
units = np.array([100, 200, 150])
profits = np.array([10,20,30])


In [81]:
units * profits

array([1000, 4000, 4500])

## Dot Product

In [82]:
# sqft
# bedroom
# location 1 Good, 0 Bad
house = np.array([[1200,3,1],
                  [1200,3,0],
                  [1000,3,0],
                  [1000,1,1]])

In [83]:
w = np.array([200,10000,50000])

In [84]:
print(house.shape)
print(w.shape)

(4, 3)
(3,)


In [85]:
print(np.dot(house,w))

[320000 270000 230000 260000]


In [86]:
print(np.sum(house * w, axis=1)) # multiplication + sum

[320000 270000 230000 260000]


In [87]:
A = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
B = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

In [88]:
print(A.shape)
print(B.shape)

(2, 4)
(2, 4)


In [89]:
print(np.dot(A, B))

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [90]:
print(np.dot(A, B.T))

[[30 30]
 [30 30]]


In [92]:
print(A @ B.T) # matrix multiplication

[[30 30]
 [30 30]]


## Broadcasting
--Broadcasting is a NumPy feature that allows you to perform operations between arrays of different shapes without manually reshaping or copying the smaller array.

--NumPy compares shapes from right to left and Compare dimensions from right to left. Each pair must be equal or one of them must be 1.

In [93]:
a = np.array([1, 2, 3]) # (3,)
b = np.array([[10], [20]]) # (2,1)

In [94]:
print(a.shape)
print(b.shape)

(3,)
(2, 1)


In [95]:
a + b
# a --> (2,3) [[1, 2, 3], [1, 2, 3]]
# b --> [[10, 10, 10], [20, 20, 20]]

array([[11, 12, 13],
       [21, 22, 23]])

## Creating arrays from existing data

In [98]:
import numpy as np

In [106]:
a = [1,2,3,4]
b = ([[1,2], [2,3]])
c = (10,20,30)

In [113]:
print(type(a))
print(type(b))
print(type(c))


<class 'list'>
<class 'list'>
<class 'tuple'>


In [101]:
a_npy = np.array(a)
print(a_npy, a_npy.dtype, type(a_npy))

[1 2 3 4] int64 <class 'numpy.ndarray'>


In [114]:
b_npy = np.array(b)
print(b_npy, b_npy.dtype, type(b_npy))

[[1 2]
 [2 3]] int64 <class 'numpy.ndarray'>


In [115]:
c_npy = np.array(c)
print(c_npy, c_npy.dtype, type(c))

[10 20 30] int64 <class 'tuple'>


In [ ]:
# vstack
# np.vstack() means vertical stack. It joins NumPy arrays row-wise (top to bottom)

a = np.array([[1,2]])
b = np.array([[3,4]])

In [118]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]]


In [119]:
print(np.hstack((a,b)))

[[1 2 3 4]]


In [120]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [121]:
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [122]:
# np.char.<function_name>()
# 1. np.add()
# "hello" + "hello"

a = np.array(['hello', 'world'])
b = np.array(['_user', '_123'])

print(np.char.add(a, b))

['hello_user' 'world_123']


In [123]:
# np.char.multiply()

print(np.char.multiply(a, 2))

['hellohello' 'worldworld']


In [124]:
# np.char.upper() / lower() / capitalize()

a = np.array(['hello', 'WORLD'])

print(np.char.upper(a)) 
print(np.char.lower(a)) 
print(np.char.capitalize(a)) 

['HELLO' 'WORLD']
['hello' 'world']
['Hello' 'World']


In [125]:
# np.char.center()

print(np.char.center(a, 11, fillchar='*'))

['***hello***' '***WORLD***']


In [126]:
a = np.array(['data_science', 'machine_learning'])

In [127]:
# np.char.replace()

print(np.char.replace(a, '_', ' '))

['data science' 'machine learning']


In [128]:
# np.char.split()

print(np.char.split(a, sep='_'))

[list(['data', 'science']) list(['machine', 'learning'])]


In [ ]:
# np.char.find() / np.char.count()
#find() returns the starting index where the given substring occurs. doesn't exist → -1

print(np.char.find(a, 'learn')) 
print(np.char.count(a, 'a'))
print(np.char.count(a, 'data'))

[-1  8]
[2 2]
[1 0]


##  statistical functions

In [130]:
data = np.array([1, 2, 3, 4, 5, 6])

In [131]:
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))
print("Min:", np.min(data))
print("Max:", np.max(data))

Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933
Variance: 2.9166666666666665
Min: 1
Max: 6


In [ ]:
#np.argmin() and np.argmax() are NumPy functions used to find the position (index) of the minimum and maximum values in an array.
print("Argmin:", np.argmin(data))
print("Argmax:", np.argmax(data))

Argmin: 0
Argmax: 5


In [134]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

print(np.mean(matrix))
print(np.mean(matrix, axis=0))
print(np.mean(matrix, axis=1))

3.5
[2.5 3.5 4.5]
[2. 5.]


In [ ]:
data = np.array([1, 3, 5, 7, 9])
print(np.percentile(data, 50)) # range 1 - 100
print(np.quantile(data, 1)) # range 0 - 1 and quantile = 100/percentile​

5.0
9


# sort, search, counting functions

In [140]:
arr = np.array([3, 6, 1, 1, 1, 1, 8, 2, 5, 6])
print("Sorted:", np.sort(arr))
print("Sorted indices:", np.argsort(arr))
print("Unique elements:", np.unique(arr))

Sorted: [1 1 1 1 2 3 5 6 6 8]
Sorted indices: [2 3 4 5 7 0 8 1 9 6]
Unique elements: [1 2 3 5 6 8]


In [141]:
#This line finds the position where 4 should be inserted into the sorted array while keeping the array sorted.
print("Insert 4 position:", np.searchsorted(np.sort(arr), 4))


Insert 4 position: 6


In [142]:
#Even though 0 and 4 aren't present, bincount() creates positions for every integer from 0 up to the maximum value.
print("Count of each element:", np.bincount(arr))


Count of each element: [0 4 1 1 0 1 2 0 1]


In [143]:
arr = np.array([1, 2, 3, 4])

for x in arr:
    print(x)

1
2
3
4


In [144]:
arr_2d = np.array([[1, 2], [3, 4]])

for x in arr_2d:
    print(x)

[1 2]
[3 4]


In [145]:
arr = np.arange(8).reshape(2,2,2)

for x in np.nditer(arr):
    print(x)

0
1
2
3
4
5
6
7


In [146]:
a = np.array([1, 2, 3])

In [147]:
b = a

In [148]:
print(id(a))
print(id(b))

4572970416
4572970416


In [149]:
b[0] = 100

In [150]:
print(a)

[100   2   3]


In [151]:
a = np.array([1, 2, 3])

In [152]:
b = a.copy()

In [153]:
b[0] = 100

In [154]:
print(a)

[1 2 3]


In [155]:
a = np.array([1, 2, 3])

b = a.view()

c = a.copy()

In [159]:
#A view creates a new array object that shares the same underlying data/memory with a.
#Because a and b share the same data.
b[0] = 10
print(a)

[10  2  3]


In [158]:
#copy() creates a completely separate copy of the data.They have separate memory.
c[0] = 20
print(a)

[10  2  3]


In [160]:
a = np.arange(5)
b = a[1:4] # view
print(np.shares_memory(a, b))

True


In [161]:
a = np.arange(5)
b = a[1:4].copy()
print(np.shares_memory(a, b))

False


In [ ]:
#ravel() tries to return a view of the original array whenever possible.
#flatten() always returns a copy.
a = np.array([[1, 2], [3, 4]])
print(a.ravel())
print(a.flatten())

[1 2 3 4]
[1 2 3 4]
