## Numpy

In [10]:
import numpy as np
import time

In [11]:
# why numpy is faster than plain python

#this is python approch code
a = list(range(100000000))
b = list(range(100000000))

start_t = time.time()
c = [x+y for x,y in zip(a,b)]
end_t = time.time()
time_taken_py = end_t - start_t

print(f"Time taken : {time_taken_py}")

Time taken : 3.4436569213867188


In [12]:
# this is numpy approch code

a = list(range(100000000))
b = list(range(100000000))
a = np.array(a)
b = np.array(b)
start_t = time.time()
c = a + b
end_t = time.time()
time_taken_np = end_t - start_t
print(f"Time takesn : {time_taken_np}")

Time takesn : 0.8262021541595459


In [13]:
#comparision which is better 

time_taken_py/time_taken_np

4.168056091417213


## 1. np.array

In [16]:
array_n1 = np.array([1,2,3])

In [17]:
print(array_n1)
print(type(array_n1))
print(type(array_n1[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [19]:
array_n2 = np.array([1,2,3], dtype=np.int8)
print(array_n2)
print(type(array_n2))
print(type(array_n2[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [ ]:
array_n2 = np.array([1,2,"3"], dtype=np.int8)
print(array_n2)
print(type(array_n2))
print(type(array_n2[2]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int16'>


In [23]:
array_n2 = np.array([1,2,"3"] , dtype=np.float16)
print(array_n2)
print(type(array_n2))
print(type(array_n2[2]))

[1. 2. 3.]
<class 'numpy.ndarray'>
<class 'numpy.float16'>
