## Numpy

In [10]:
import numpy as np
import time

In [11]:
# why numpy is faster than plain python

#this is python approch code
a = list(range(100000000))
b = list(range(100000000))

start_t = time.time()
c = [x+y for x,y in zip(a,b)]
end_t = time.time()
time_taken_py = end_t - start_t

print(f"Time taken : {time_taken_py}")

Time taken : 3.4436569213867188


In [12]:
# this is numpy approch code

a = list(range(100000000))
b = list(range(100000000))
a = np.array(a)
b = np.array(b)
start_t = time.time()
c = a + b
end_t = time.time()
time_taken_np = end_t - start_t
print(f"Time takesn : {time_taken_np}")

Time takesn : 0.8262021541595459


In [13]:
#comparision which is better 

time_taken_py/time_taken_np

4.168056091417213


## 1. np.array

In [16]:
array_n1 = np.array([1,2,3])

In [17]:
print(array_n1)
print(type(array_n1))
print(type(array_n1[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [19]:
array_n2 = np.array([1,2,3], dtype=np.int8)
print(array_n2)
print(type(array_n2))
print(type(array_n2[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [ ]:
array_n2 = np.array([1,2,"3"], dtype=np.int8)
print(array_n2)
print(type(array_n2))
print(type(array_n2[2]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int16'>


In [23]:
array_n2 = np.array([1,2,"3"] , dtype=np.float16)
print(array_n2)
print(type(array_n2))
print(type(array_n2[2]))

[1. 2. 3.]
<class 'numpy.ndarray'>
<class 'numpy.float16'>


## np.arange(start, stop, step)
- it will give number in given range

In [25]:
print(np.arange(5))
print(np.arange(1, 10, 2))

np_arange = np.arange(1,10,2)
print(type(np_arange))

[0 1 2 3 4]
[1 3 5 7 9]
<class 'numpy.ndarray'>


## np.linspace(start, stop, num=x)
- it will create number in given range equally spaced

In [29]:
np_linspace = np.linspace(1,100,4)
print(np_linspace)
print(type(np_linspace))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [30]:
for i in np.linspace(1,10,10):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


## np.zeros(shape)

In [32]:
npz_1 = np.zeros(5)
print(npz_1)

[0. 0. 0. 0. 0.]


In [ ]:
#it will give dimension
npz_1.ndim

1

In [35]:
npz_2 = np.zeros((5,5))
print(npz_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
npz_2.ndim

2

In [37]:
npz_3 = np.zeros((5,5,5))
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [38]:
npz_3.ndim

3