In [115]:
import numpy as np

In [116]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [117]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [118]:
np.zeros((5,5)).shape # it will give shape

(5, 5)

In [119]:
np.zeros((5,5)).ndim # it will give dimenssion

2

## np.ones()

In [120]:
np.ones(5) # defult datatpye is float

array([1., 1., 1., 1., 1.])

In [121]:
np.ones(5).ndim

1

In [122]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [123]:
np.ones((5,5)).shape

(5, 5)

In [124]:
np.ones((5,5)).ndim

2

In [125]:
np.ones(5 , dtype=np.int8)

array([1, 1, 1, 1, 1], dtype=int8)

In [126]:
np.ones((5,5), dtype=np.int8) # dtpye is used to change datatype

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

## np.full(size, value)
-- np.full(shape, fill_value)

In [127]:
# list of size 10, all filled with value 5
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [128]:
np.full((5,5), 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [129]:
np.full((5,5),100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

## np.eye(n)
-- np.eye() is a NumPy function used to create an identity matrix or a matrix with 1s on a specified diagonal and 0s elsewhere.

In [130]:
np.eye(6,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [131]:
np.eye(6,6, dtype=np.int8)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int8)

In [132]:
np.eye(6,6,4)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [133]:
np.eye(6,6,4,dtype=np.int8)

array([[0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int8)

In [134]:
# different row and col
np.eye(3, 4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [135]:
# by default no. of col is same as row
np.eye(6)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [136]:
np.eye((6,6),4) # this give error

TypeError: 'tuple' object cannot be interpreted as an integer

## np.empty(shape)
-- np.empty() creates a  NumPy array without initializing its values.

In [ ]:
np.empty((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.empty((5,5),dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [ ]:
np.empty((5,5), dtype=int)

array([[4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408]])

In [ ]:
import time

perf_counter() is used to get high-resolution time counter.

In [ ]:
start_e = time.perf_counter()
np.empty((5,5))
end_e = time.perf_counter()
total_e = end_e - start_e
print(total_e)

3.612501313909888e-05


In [ ]:
start_we = time.perf_counter()
np.ones((5,5))
end_we = time.perf_counter()
total_we = end_we-start_we
print(total_we)

9.654200403019786e-05


## np.random.rand(shape)
-- it will give random number between 0 and 1

In [ ]:
np.random.rand(5,5)

array([[0.51901056, 0.11942832, 0.95228871, 0.74200826, 0.17164341],
       [0.80319048, 0.66733971, 0.5944338 , 0.03844422, 0.57747408],
       [0.82562502, 0.15096019, 0.12109048, 0.13235169, 0.35675339],
       [0.74107619, 0.48417799, 0.30651058, 0.32316027, 0.5813827 ],
       [0.4087706 , 0.96256812, 0.57387992, 0.1835214 , 0.03316593]])

In [ ]:
a = np.random.rand(10)*10

In [ ]:
a.tolist()  #it will convert it into list

[0.79315746048917,
 0.790118818834793,
 0.4402180876974304,
 8.580301316464727,
 6.988636268462915,
 1.940263020712094,
 0.14950411749521053,
 5.578566807085488,
 2.0303792089781947,
 1.221832881312226]

In [ ]:
a

array([0.79315746, 0.79011882, 0.44021809, 8.58030132, 6.98863627,
       1.94026302, 0.14950412, 5.57856681, 2.03037921, 1.22183288])

In [ ]:
# print only integer parts
a = [int(i) for i in a]

In [ ]:
a

[0, 0, 0, 8, 6, 1, 0, 5, 2, 1]

In [ ]:
# it will create random integer value in given range
np.random.randint(1,11,10)

array([4, 2, 3, 7, 6, 9, 3, 1, 8, 7])

# Questions
- A 1D array of numbers from 0 to 9
- A 3x3 matrix of all 5s
- A 4x4 identity matrix
- 10 evenly spaced numbers between 1 and 100
- A 2x2 array with random values between 0 and 1

In [ ]:
# Answer
#A 1D array of numbers from 0 to 9
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#A 3x3 matrix of all 5s
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#A 4x4 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10, dtype=np.int8)

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100], dtype=int8)

In [ ]:
#A 2x2 array with random values between 0 and 1
np.random.rand(2,2)

array([[0.3090797 , 0.58187021],
       [0.07463202, 0.89346036]])

## Numpy Attributes

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])

In [ ]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#it will give number of rows and columns
arr.shape

(2, 3)

In [ ]:
#it will give how many elements in array
arr.size

6

In [ ]:
# it will give dimension of array
arr.ndim

2

In [ ]:
# it will give data type
arr.dtype

dtype('int64')

## ndarray itemsize


In [ ]:
# it will give size in bytes of one element
arr.itemsize

8

In [ ]:
# 1 gb --> 1024 mb
# 1 mb --> 1024 kb
# 1 kb --> 1024 bytes
# 1 byte --> 8 bit

# Java
# - int --> 4 bytes
# - float --> 4 bytes
# - char --> 1 byte

In [ ]:
# gives size in Bytes
import sys

print("Size of int:", sys.getsizeof(int()))  # Integer
print("Size of float:", sys.getsizeof(float()))  # Floating-point number
print("Size of str:", sys.getsizeof(str()))  # String
print("Size of list:", sys.getsizeof(list()))  # List
print("Size of tuple:", sys.getsizeof(tuple()))  # Tuple
print("Size of dict:", sys.getsizeof(dict()))  # Dictionary
print("Size of set:", sys.getsizeof(set()))  # Set


Size of int: 28
Size of float: 24
Size of str: 41
Size of list: 56
Size of tuple: 40
Size of dict: 64
Size of set: 216


In [ ]:
# gives total bytes consumed by the array
arr.nbytes

48

In [ ]:
# Transpose of array
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# Exercise
arr1 = np.full((3,5), 3)
print(arr1)
print(arr1.T)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


## Indexing and slicing

In [ ]:
arr2 = np.array([10, 20, 30, 40, 50, 60])

In [ ]:
print(arr2[0])
print(arr2[-1])

10
60


In [ ]:
print(arr2[2:4])
print(arr2[:3])
print(arr2[0:3])

[30 40]
[10 20 30]
[10 20 30]


In [ ]:
# (start with 0 and step size 2)
#(start:end:step)

print(arr2[::2])

[10 30 50]


In [ ]:
#(start:end:step)
print(arr2[1:5:2])

[20 40]


In [139]:
import numpy as np

In [140]:
mat = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

In [141]:
print(mat)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(mat[0][1]) # chained indexing
print(mat[0, 1]) # direct indexing

2
2


In [150]:
print(mat[1])
print(mat[:,2]) # it will give second index element of all rows
print(mat[0:2,2])
print(mat[:,-1])

[4 5 6]
[3 6 9]
[3 6]
[3 6 9]


In [151]:
print(mat[0:2, 1:])

[[2 3]
 [5 6]]


In [152]:
arr_temp = np.array([1,2,3,4,5,6,7,8,9])

In [153]:
# reverse the array
print(arr_temp[::-1])

[9 8 7 6 5 4 3 2 1]


In [154]:
# reverse matrix
print(mat[::-1,::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [155]:
arr3 = np.array([5,10,15,20,25])

In [157]:
arr3>10

array([False, False,  True,  True,  True])

In [ ]:
print(arr3[arr3>10]) # boolean indexing

[15 20 25]


In [160]:
index = [0,3,4]
arr3[index]

array([ 5, 20, 25])

In [ ]:
# update value
arr3[0] = 50
print(arr3) 

[50 10 15 20 25]


## indexing with np.where()
-- np.where() is used to find the positions (indices) where a condition is True

In [162]:
arr4 = np.array([10,15,20,25,30])

In [163]:
idx = np.where(arr4>20)
print(idx)

(array([3, 4]),)


In [165]:
print(arr4[idx])

[25 30]


## array reshaping and resizing

In [166]:
arr5 = np.array([1,2,3,4,5,6])

In [167]:
arr4.shape

(5,)

In [171]:
# it will change the shape of array
reshaped = arr5.reshape((2,3))

In [172]:
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
reshaped = arr5.reshape((3,3)) # it give error
print(reshaped)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [175]:
arr6 = np.array([1, 2, 3, 4, 5, 6,7,8,9,10,11,12])

In [ ]:
# it will consider no. of col accordingly and it will not change original array
reshaped = arr6.reshape(3,-1)

In [179]:
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [181]:
reshaped.shape

(3, 4)

In [191]:
arr7 = np.array([[1,2], [3,4]])

In [192]:
arr_flatten = arr7.flatten() # it will change multidim array in 1-d array and flatten() creates a copy

In [198]:
arr_flatten

array([1, 2, 3, 4])

In [199]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.resize((2,3)) #it will change original array

In [201]:
a

array([[1, 2, 3],
       [4, 0, 0]])

In [202]:
a = np.array([1, 2, 3, 4])

In [203]:
a.resize((2,1))

In [204]:
a

array([[1],
       [2]])

In [205]:
print(a)

[[1]
 [2]]


In [206]:
# reshape will throw error if values are insufficient
# resize will truncate or add with zeros

In [ ]:
# read from first bracket and check how many element in first then second then third
a = np.array([[[1],[2],[3]], [[1],[2],[3]]])
print(a.shape)

(2, 3, 1)


In [208]:
a = np.array([[1],[2],[3]])
print(a.shape)

(3, 1)


In [ ]:
a = np.array([[[1],[2],[3]], [[1],[2],[3]]])
print(a.shape)
b = np.squeeze(a) # squeeze() removes dimensions whose size is 1
print(b.shape)
print(b)

(2, 3, 1)
(2, 3)
[[1 2 3]
 [1 2 3]]


In [210]:
a = np.array([[[1],[2],[3]]])
print(a.shape)
b = np.squeeze(a, axis=0)
print(b.shape)
print(b)

(1, 3, 1)
(3, 1)
[[1]
 [2]
 [3]]


In [211]:
b = np.array([b])
print(b)

[[[1]
  [2]
  [3]]]


In [212]:
a = np.array([
                [1,2,3],
                [1,2,3],
                [1,2,3]
            ])

In [213]:
print(np.sum(a, axis=0)) # rows wise

[3 6 9]


In [214]:
print(np.sum(a, axis=1)) # column wise

[6 6 6]
